### ISSUE TITLE
Cannot be built with Egison 3.10.0

### ISSUE THREAD

**Issue by greymd** [egison/egison-tutorial#12]
```
$ cabal v2-build
Resolving dependencies...
Build profile: -w ghc-8.8.1 -O1
In order, the following will be built (use -v for more details):
 - egison-tutorial-3.9.3 (exe:egison-tutorial) (configuration changed)
Configuring executable 'egison-tutorial' for egison-tutorial-3.9.3..
Preprocessing executable 'egison-tutorial' for egison-tutorial-3.9.3..
Building executable 'egison-tutorial' for egison-tutorial-3.9.3..
[1 of 2] Compiling Paths_egison_tutorial ( /egison-tutorial/dist-newstyle/build/x86_64-linux/ghc-8.8.1/egison-tutorial-3.9.3/x/egison-tutorial/build/egison-tutorial/autogen/Paths_egison_tutorial.hs, /egison-tutorial/dist-newstyle/build/x86_64-linux/ghc-8.8.1/egison-tutorial-3.9.3/x/egison-tutorial/build/egison-tutorial/egison-tutorial-tmp/Paths_egison_tutorial.o ) [Optimisation flags changed]
[2 of 2] Compiling Main             ( Main.hs, /egison-tutorial/dist-newstyle/build/x86_64-linux/ghc-8.8.1/egison-tutorial-3.9.3/x/egison-tutorial/build/egison-tutorial/egison-tutorial-tmp/Main.o ) [Optimisation flags changed]

Main.hs:47:35: error:
    Not in scope: ‘ET.defaultOption’
    Module ‘Language.Egison.Types’ does not export ‘defaultOption’.
   |
47 |                 env <- initialEnv ET.defaultOption
   |                                   ^^^^^^^^^^^^^^^^

Main.hs:227:45: error:
    Not in scope: ‘ET.defaultOption’
    Module ‘Language.Egison.Types’ does not export ‘defaultOption’.
    |
227 |         result <- liftIO $ runEgisonTopExpr ET.defaultOption env topExpr
    |                                             ^^^^^^^^^^^^^^^^
```

I guess this is caused by https://github.com/egison/egison/commit/304dfe80c5b49434b03348824fe95566d22821020

**Comment by egisatoshi** [comment]
Thank you! I'll fix it now.
